name: Publish Homey App
# Workflows disabled - using dummy trigger that never runs
on:
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run (disabled)'
        required: false
        default: 'false'

jobs:
  main:
    name: Publish Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish Homey App
        uses: athombv/github-action-homey-app-publish@master
        id: publish
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}

      - name: URL
        run: |
          echo "Manage your app at ${{ steps.publish.outputs.url }}." >> $GITHUB_STEP_SUMMARY
