name: Validate Homey App
# Workflows disabled - using dummy trigger that never runs
on:
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run (disabled)'
        required: false
        default: 'false'

jobs:
  main:
    name: Validate Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: athombv/github-action-homey-app-validate@master
        with:
          level: publish
